# PYSPARK

In [1]:
from pyspark.sql import SparkSession
from pathlib import Path
from pyspark.sql import functions as F

In [2]:
spark = SparkSession.builder \
    .appName("Capstone Dataset Inspection") \
    .getOrCreate()

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
26/09/21 12:24:31 WARN Utils: Your hostname, EDP-100-1289-CheskaOlympia.local, resolves to a loopback address: 127.0.0.1; using 192.168.68.115 instead (on interface en0)
26/09/21 12:24:31 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/pyspark/testing/utils.py:127: FutureWarning: PySpark does not yet fully support pandas >= 3.0.0. Some features may not work correctly. It is recommended to use pandas < 3.0.0 for now.
  require_minimum_pandas_version()
26/09/21 12:24:32 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [3]:
df_october = (
    spark.read
    .option("header", True)
    .option("inferSchema", True)
    .csv("/Users/francheska.olympia/Downloads/training/capstone dataset/2019-Oct.csv")
)

df_november = (
    spark.read
    .option("header", True)
    .option("inferSchema", True)
    .csv("/Users/francheska.olympia/Downloads/training/capstone dataset/2019-Nov.csv")
)

## October dataset

In [4]:
from pyspark.sql import functions as F

df_october.show(5)

+-------------------+----------+----------+-------------------+--------------------+--------+-------+---------+--------------------+
|         event_time|event_type|product_id|        category_id|       category_code|   brand|  price|  user_id|        user_session|
+-------------------+----------+----------+-------------------+--------------------+--------+-------+---------+--------------------+
|2019-10-01 08:00:00|      view|  44600062|2103807459595387724|                NULL|shiseido|  35.79|541312140|72d76fde-8bb3-4e0...|
|2019-10-01 08:00:00|      view|   3900821|2053013552326770905|appliances.enviro...|    aqua|   33.2|554748717|9333dfbd-b87a-470...|
|2019-10-01 08:00:01|      view|  17200506|2053013559792632471|furniture.living_...|    NULL|  543.1|519107250|566511c2-e2e3-422...|
|2019-10-01 08:00:01|      view|   1307067|2053013558920217191|  computers.notebook|  lenovo| 251.74|550050854|7c90fc70-0e80-459...|
|2019-10-01 08:00:04|      view|   1004237|2053013555631882655|electronics.smart...|   apple|1081.98|535871217|c6bd7419-2748-4c5...|
+-------------------+----------+----------+-------------------+--------------------+--------+-------+---------+--------------------+
only showing top 5 rows

### check data schema

In [15]:
df_october[['user_session', 'event_type']].show(5)

+--------------------+----------+
|        user_session|event_type|
+--------------------+----------+
|72d76fde-8bb3-4e0...|      view|
|9333dfbd-b87a-470...|      view|
|566511c2-e2e3-422...|      view|
|7c90fc70-0e80-459...|      view|
|c6bd7419-2748-4c5...|      view|
+--------------------+----------+
only showing top 5 rows

In [5]:
df_october.printSchema()

root
 |-- event_time: timestamp (nullable = true)
 |-- event_type: string (nullable = true)
 |-- product_id: integer (nullable = true)
 |-- category_id: long (nullable = true)
 |-- category_code: string (nullable = true)
 |-- brand: string (nullable = true)
 |-- price: double (nullable = true)
 |-- user_id: integer (nullable = true)
 |-- user_session: string (nullable = true)

### check null values

In [6]:
df_october.select(
    [F.count(F.when(F.col(column).isNull(), column)).alias(column)
     for column in df_october.columns]
).show()

+----------+----------+----------+-----------+-------------+-------+-----+-------+------------+
|event_time|event_type|product_id|category_id|category_code|  brand|price|user_id|user_session|
+----------+----------+----------+-----------+-------------+-------+-----+-------+------------+
|         0|         0|         0|          0|     13515609|6113008|    0|      0|           2|
+----------+----------+----------+-----------+-------------+-------+-----+-------+------------+

## November dataset

In [7]:
df_november.show(5)

+-------------------+----------+----------+-------------------+--------------------+------+------+---------+--------------------+
|         event_time|event_type|product_id|        category_id|       category_code| brand| price|  user_id|        user_session|
+-------------------+----------+----------+-------------------+--------------------+------+------+---------+--------------------+
|2019-11-01 08:00:00|      view|   1003461|2053013555631882655|electronics.smart...|xiaomi|489.07|520088904|4d3b30da-a5e4-49d...|
|2019-11-01 08:00:00|      view|   5000088|2053013566100866035|appliances.sewing...|janome|293.65|530496790|8e5f4f83-366c-4f7...|
|2019-11-01 08:00:01|      view|  17302664|2053013553853497655|                NULL| creed| 28.31|561587266|755422e7-9040-477...|
|2019-11-01 08:00:01|      view|   3601530|2053013563810775923|appliances.kitche...|    lg|712.87|518085591|3bfb58cd-7892-48c...|
|2019-11-01 08:00:01|      view|   1004775|2053013555631882655|electronics.smart...|xiaomi|183.27|558856683|313628f1-68b8-460...|
+-------------------+----------+----------+-------------------+--------------------+------+------+---------+--------------------+
only showing top 5 rows

### check dataset schema

In [8]:
df_november.printSchema()

root
 |-- event_time: timestamp (nullable = true)
 |-- event_type: string (nullable = true)
 |-- product_id: integer (nullable = true)
 |-- category_id: long (nullable = true)
 |-- category_code: string (nullable = true)
 |-- brand: string (nullable = true)
 |-- price: double (nullable = true)
 |-- user_id: integer (nullable = true)
 |-- user_session: string (nullable = true)

### check null values

In [9]:
df_november.select(
    [F.count(F.when(F.col(column).isNull(), column)).alias(column)
     for column in df_november.columns]
).show()

+----------+----------+----------+-----------+-------------+-------+-----+-------+------------+
|event_time|event_type|product_id|category_id|category_code|  brand|price|user_id|user_session|
+----------+----------+----------+-----------+-------------+-------+-----+-------+------------+
|         0|         0|         0|          0|     21898171|9218235|    0|      0|          10|
+----------+----------+----------+-----------+-------------+-------+-----+-------+------------+

## overview -- side-by-side

In [10]:
print("october null values")
df_october.select(
    [F.count(F.when(F.col(column).isNull(), column)).alias(column)
     for column in df_october.columns]
).show()

print("november null values")
df_november.select(
    [F.count(F.when(F.col(column).isNull(), column)).alias(column)
     for column in df_november.columns]
).show()

october null values

+----------+----------+----------+-----------+-------------+-------+-----+-------+------------+
|event_time|event_type|product_id|category_id|category_code|  brand|price|user_id|user_session|
+----------+----------+----------+-----------+-------------+-------+-----+-------+------------+
|         0|         0|         0|          0|     13515609|6113008|    0|      0|           2|
+----------+----------+----------+-----------+-------------+-------+-----+-------+------------+

november null values

+----------+----------+----------+-----------+-------------+-------+-----+-------+------------+
|event_time|event_type|product_id|category_id|category_code|  brand|price|user_id|user_session|
+----------+----------+----------+-----------+-------------+-------+-----+-------+------------+
|         0|         0|         0|          0|     21898171|9218235|    0|      0|          10|
+----------+----------+----------+-----------+-------------+-------+-----+-------+------------+

# PANDAS

In [16]:
import pandas as pd

october_path = "/Users/francheska.olympia/Downloads/training/capstone dataset/2019-Oct.csv"
november_path = "/Users/francheska.olympia/Downloads/training/capstone dataset/2019-Nov.csv"

october_df = pd.read_csv(october_path, header=0)
november_df = pd.read_csv(november_path, header=0)

## October df inspection

In [17]:
october_df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,view,44600062,2103807459595387724,NaN,shiseido,35.79,541312140,72d76fde-8bb3-4e00-8c23-a032dfed738c
1,2019-10-01 00:00:00 UTC,view,3900821,2053013552326770905,appliances.environment.water_heater,aqua,33.20,554748717,9333dfbd-b87a-4708-9857-6336556b0fcc
2,2019-10-01 00:00:01 UTC,view,17200506,2053013559792632471,furniture.living_room.sofa,NaN,543.10,519107250,566511c2-e2e3-422b-b695-cf8e6e792ca8
3,2019-10-01 00:00:01 UTC,view,1307067,2053013558920217191,computers.notebook,lenovo,251.74,550050854,7c90fc70-0e80-4590-96f3-13c02c18c713
4,2019-10-01 00:00:04 UTC,view,1004237,2053013555631882655,electronics.smartphone,apple,1081.98,535871217,c6bd7419-2748-4c56-95b4-8cec9ff8b80d

In [18]:
october_df.info()
october_df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 42448764 entries, 0 to 42448763
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   event_time     str
 1   event_type     str
 2   product_id     int64
 3   category_id    int64
 4   category_code  str
 5   brand          str
 6   price          float64
 7   user_id        int64
 8   user_session   str
dtypes: float64(1), int64(3), str(5)
memory usage: 2.8 GB

         product_id   category_id         price       user_id
count  4.244876e+07  4.244876e+07  4.244876e+07  4.244876e+07
mean   1.054993e+07  2.057404e+18  2.903237e+02  5.335371e+08
std    1.188191e+07  1.843926e+16  3.582692e+02  1.852374e+07
min    1.000978e+06  2.053014e+18  0.000000e+00  3.386938e+07
25%    1.005157e+06  2.053014e+18  6.598000e+01  5.159043e+08
50%    5.000470e+06  2.053014e+18  1.629300e+02  5.296965e+08
75%    1.600030e+07  2.053014e+18  3.585700e+02  5.515788e+08
max    6.050001e+07  2.175420e+18  2.574070e+03  5.662809e+08

In [19]:
october_df.isnull().sum()

event_time              0
event_type              0
product_id              0
category_id             0
category_code    13515609
brand             6117080
price                   0
user_id                 0
user_session            2
dtype: int64

## November dataframe inspection

In [20]:
november_df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:00:00 UTC,view,1003461,2053013555631882655,electronics.smartphone,xiaomi,489.07,520088904,4d3b30da-a5e4-49df-b1a8-ba5943f1dd33
1,2019-11-01 00:00:00 UTC,view,5000088,2053013566100866035,appliances.sewing_machine,janome,293.65,530496790,8e5f4f83-366c-4f70-860e-ca7417414283
2,2019-11-01 00:00:01 UTC,view,17302664,2053013553853497655,NaN,creed,28.31,561587266,755422e7-9040-477b-9bd2-6a6e8fd97387
3,2019-11-01 00:00:01 UTC,view,3601530,2053013563810775923,appliances.kitchen.washer,lg,712.87,518085591,3bfb58cd-7892-48cc-8020-2f17e6de6e7f
4,2019-11-01 00:00:01 UTC,view,1004775,2053013555631882655,electronics.smartphone,xiaomi,183.27,558856683,313628f1-68b8-460d-84f6-cec7a8796ef2

In [21]:
november_df.info()
november_df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 67501979 entries, 0 to 67501978
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   event_time     str
 1   event_type     str
 2   product_id     int64
 3   category_id    int64
 4   category_code  str
 5   brand          str
 6   price          float64
 7   user_id        int64
 8   user_session   str
dtypes: float64(1), int64(3), str(5)
memory usage: 4.5 GB

         product_id   category_id         price       user_id
count  6.750198e+07  6.750198e+07  6.750198e+07  6.750198e+07
mean   1.251406e+07  2.057898e+18  2.924593e+02  5.386397e+08
std    1.725741e+07  2.012549e+16  3.556745e+02  2.288516e+07
min    1.000365e+06  2.053014e+18  0.000000e+00  1.030022e+07
25%    1.305977e+06  2.053014e+18  6.924000e+01  5.164762e+08
50%    5.100568e+06  2.053014e+18  1.657700e+02  5.350573e+08
75%    1.730075e+07  2.053014e+18  3.603400e+02  5.610794e+08
max    1.000286e+08  2.187708e+18  2.574070e+03  5.799699e+08

In [22]:
november_df.isnull().sum()

event_time              0
event_type              0
product_id              0
category_id             0
category_code    21898171
brand             9224078
price                   0
user_id                 0
user_session           10
dtype: int64